#
input_ports:
    - input
#
output_ports:
    - output
#
parameters:
    lynxi_info/type:
        widget: string
        value: 'lx_variant_settings'
        tool_tip: '...'

    lynxi_settings/render_camera:
        widget: path
        value: ''
        tool_tip: '...'

    lynxi_settings/render_resolution:
        widget: resolution
        value: '2048x2048'
        tool_tip: '...'

    lynxi_settings/render_start_frame:
        widget: float
        value: 1.0
        tool_tip: '...'

    lynxi_settings/render_end_frame:
        widget: float
        value: 240.0
        tool_tip: '...'

    lynxi_variants/camera:
        widget: string
        value: ''
        tool_tip: '...'

    lynxi_variants/geometry:
        widget: enumerate
        value: ['asset', 'shot']
        tool_tip: '...'

    lynxi_variants/look:
        widget: enumerate
        value: ['asset', 'shot']
        tool_tip: '...'

    lynxi_variants/rotations/camera_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    lynxi_variants/rotations/camera_start_frame:
        widget: float
        value: 1.0
        tool_tip: '...'

    lynxi_variants/rotations/camera_end_frame:
        widget: float
        value: 120.0
        tool_tip: '...'

    lynxi_variants/rotations/camera_frame_offset:
        widget: float
        value: 0.0
        tool_tip: '...'

    lynxi_variants/rotations/light_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    lynxi_variants/rotations/light_start_frame:
        widget: float
        value: 121.0
        tool_tip: '...'

    lynxi_variants/rotations/light_end_frame:
        widget: float
        value: 240.0
        tool_tip: '...'

    lynxi_variants/rotations/light_frame_offset:
        widget: float
        value: 1003.0
        tool_tip: '...'