#
input_ports:
    - input
#
output_ports:
    - output
#
parameters:
    reset:
        widget: button
        value: 'import lxkatana.scripts as ktn_scripts; ktn_scripts.LxRenderSettings(node).set_reset()'
        tool_tip: 'press to rest all parameters'
    #
    render_settings/camera_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    render_settings/camera:
        widget: path
        value: ''
        tool_tip: '...'

    render_settings/resolution_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    render_settings/resolution:
        widget: resolution
        value: '512x512'
        tool_tip: '...'

    render_settings/override_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    render_settings/override:
        widget: script
        value: ''
        tool_tip: '...'
    #
    arnold_render_settings/stats_file_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    arnold_render_settings/stats_file:
        widget: file
        value: '/temp/<layer>.<quality>.<look-pass>.<light-pass>.<camera>/stats.####.json'
        tool_tip: '...'

    arnold_render_settings/set_stats_file:
        widget: button
        value: 'import lxkatana.scripts as ktn_scripts; ktn_scripts.LxRenderSettings(node).set_stats_file()'
        tool_tip: '...'

    arnold_render_settings/profile_file_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    arnold_render_settings/profile_file:
        widget: file
        value: '/temp/<layer>.<quality>.<look-pass>.<light-pass>.<camera>/profile.####.json'
        tool_tip: '...'

    arnold_render_settings/set_profile_file:
        widget: button
        value: 'import lxkatana.scripts as ktn_scripts; ktn_scripts.LxRenderSettings(node).set_profile_file()'
        tool_tip: '...'

    arnold_render_settings/override_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    arnold_render_settings/override:
        widget: script
        value: ''
        tool_tip: '...'
    #
    variables/over:
        widget: boolean
        value: False
        tool_tip: '...'
    #
    lynxi_settings/render_output_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    lynxi_settings/render_output:
        widget: file
        value: '/temp/<layer>.<quality>.<look-pass>.<light-pass>.<camera>/<render-pass>.####.exr'
        tool_tip: '...'

    lynxi_settings/set_render_output:
      widget: button
      value: 'import lxkatana.scripts as ktn_scripts; ktn_scripts.LxRenderSettings(node).set_render_output()'
      tool_tip: '...'

    lynxi_settings/override_enable:
        widget: boolean
        value: False
        tool_tip: '...'

    lynxi_settings/override:
        widget: script
        value: ''
        tool_tip: '...'
    # variants
    lynxi_variants/layer:
        widget: string
        value: 'master'
        tool_tip: '...'

    lynxi_variants/quality:
        widget: string
        value: 'med'
        tool_tip: '...'

    lynxi_variants/percent:
        widget: enumerate
        value: ['100%', '25%', '50%', '75%', '125%', '150%', '175%', '200%']
        tool_tip: '...'

    lynxi_variants/camera:
        widget: string
        value: 'full_body'
        tool_tip: '...'

    lynxi_variants/look_pass:
        widget: string
        value: 'default'
        tool_tip: '...'

    lynxi_variants/light_pass:
        widget: string
        value: 'all'
        tool_tip: '...'

    lynxi_variants/customize:
        widget: script
        value: ''
        tool_tip: '...'
